---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://boardingpass.network" # The base hostname & protocol for your site, e.g. http://example.com

title: Boarding Pass
logo: /assets/images/logo.jpg
logo-small: /assets/images/boton-bp.jpg
description: # Add your awesome description
copyright: "Copyright © 2023 Boarding Pass"
# Preloader
preloader: false # To disable preloader change value to false

locale: "es-ES"
timezone: America/Caracas

menu:
  - name: Home
    url: /
  - name: Entérate
    url: /enterate/
  - name: Opinión
    url: /opinion/
  - name: Rutas
    url: /rutas/
    submenu:
     - name: VIP's
       url: /rutas-vips/
     - name: Aérea
       url: /rutas-aereas/
     - name: Marítima
       url: /rutas-maritimas/
     - name: Terrestre
       url: /rutas-terrestres/
  - name: Salte del radar
    url: /salte-del-radar/
  - name: Destinos
    url: /destinos/
  - name: Directorio
    url: /directorio/
  - name: Acerca
    url: /acerca/
  - name: Contacto
    url: /contacto/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: Somos un boarding pass p
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Boarding Pass

#-------------------------------
# Contact Info
contact:
  email: contacto@boardingpass.network
  whatsapp: +58 426 5203724
  walink: 584265203724
  address:
    city: Caracas
    street: 

# Contact Form
contact-form: f/xwkdoldl

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: G-3PLT3KJYNC

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
#  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives
  - jekyll-paginate-v2

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

#Collections
collections:
  directorio:
    output: true
    permalink: /directorio/:path/
  review:
    output: true
    permalink: /review/:path/

pagination:
  enabled: true
  per_page: 30
  permalink: '/:num/'
  title: ':title | :num de :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2
    
# iconos servicios directorio
servicios_iconos:
  "Asesoría Personalizada de Viajes": "fas fa-comments"
  "Excursiones Locales": "fas fa-hiking"
  "Guía Turística": "fas fa-map"
  "Hospedaje": "fas fa-bed"
  "Organización de Viajes": "fas fa-suitcase"
  "Organización de Viajes de Turismo": "fas fa-globe-americas"
  "Resolución de Incidencias": "fas fa-exclamation-circle"
  "Servicio de Reservación": "fas fa-calendar-check"
  "Traslados": "fas fa-car"
  "Venta de Boletos Aéreos Internacionales": "fas fa-plane-departure"
  "Venta de Boletos Aéreos Nacionales": "fas fa-plane"
  "Viajes Internacionales": "fas fa-globe"
  "Viajes Nacionales": "fas fa-flag"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - ".gitignore"

prose:
  ignore: [
    '_layouts',
    '_includes',
    '_site',
    '_pages',
    '.sass-cache',
    '_config.yml',
    '.gitignore',
    '404.html',
    'index.html',
    'assets',
    'CNAME',
    'robots.txt',
    'LICENSE',
    'readme.md',
    'Gemfile',
    'Gemfile.lock'
  ]
  siteurl: "https://boardingpass.network/page/"
  media: 'assets/images/contenido'
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Ingresa el título la publicación
          type: text
      - name: date
        field:
          element: text
          label: Fecha de la publicación
          value: CURRENT_DATETIME
      - name: description
        field:
          element: text
          label: Ingresa la descripción de la publicación
          type: text
      - name: featured
        field:
          element: checkbox
          label: Publicación resaltada
          help: Puedes destacar la publicación en la página principal
          value: false
      - name: published
        field:
          element: checkbox
          label: ¿Publicar?
          help: Puedes publicar directamente o dejar como borrador
          value: true
      - name: image
        field: 
          element: text
          label: Indica la ruta de la imagen de la publicación
          value: ""
      - name: image-text
        field: 
          element: text
          label: Indica el texto que describe la foto
          value: ""
      - name: banner-image
        field: 
          element: text
          label: Indica la ruta del banner
          value: ""
      - name: banner-alt
        field: 
          element: text
          label: Indica el texto alternativo del banner
          value: ""
      - name: banner-url
        field: 
          element: text
          label: Indica el link del banner
          value: ""
      - name: author
        field:
          element: text
          label: Nombre del autor
          value: ""
      - name: categories
        field:
          element: multiselect
          label: Selecciona las categoría de la publicación
          help: Puedes seleccionar varias categoría
          options:
            - name: 'Destinos'
              value: 'destinos'
            - name: 'Directorio'
              value: 'directorio'
            - name: 'Entérate'
              value: 'enterate'
            - name: 'Opinión'
              value: 'opinion'
            - name: "Rutas-VIP's"
              value: 'rutas-vips'
            - name: 'Rutas-Aéreas'
              value: 'rutas-aereas'
            - name: 'Rutas-Marítimas'
              value: 'rutas-maritimas'
            - name: 'Rutas-Terrestres'
              value: 'rutas-terrestres'
            - name: 'Salte del radar'
              value: 'salte-del-radar'
          alterable: false
    _directorio:
      - name: title
        field:
          element: text
          label: Ingresa el nombre 
          type: text
      - name: date
        field:
          element: text
          label: Fecha de creación
          value: CURRENT_DATETIME
      - name: published
        field:
          element: checkbox
          label: ¿Publicar?
          help: Puedes publicar directamente o dejar como borrador
          value: true
      - name: region
        field:
          element: select
          label: Selecciona la Región 
          help: Puedes seleccionar una sola Región
          options:
            - name: 'Los Andes'
              value: 'Los Andes'
            - name: 'Lago de Maracaibo'
              value: 'Lago de Maracaibo'
            - name: 'Guayana'
              value: 'Guayana'
            - name: 'Centro-Norte'
              value: 'Centro-Norte'
            - name: 'Centro-Occidental'
              value: 'Centro-Occidental'
            - name: 'Nor-Oriental'
              value: 'Nor-Oriental'
            - name: 'Los Llanos'
              value: 'Los Llanos'
            - name: 'Llanura Deltaica'
              value: 'Llanura Deltaica'
            - name: 'Nacional'
              value: 'Nacional'
          alterable: false
      - name: state
        field:
          element: select
          label: Selecciona el Estado 
          help: Puedes seleccionar un solo Estado
          options:
            - name: 'Amazonas'
              value: 'Amazonas'
            - name: 'Anzoátegui'
              value: 'Anzoátegui'
            - name: 'Apure'
              value: 'Apure'
            - name: 'Aragua'
              value: 'Aragua'
            - name: 'Barinas'
              value: 'Barinas'
            - name: 'Bolívar'
              value: 'Bolívar'
            - name: 'Carabobo'
              value: 'Carabobo'
            - name: 'Cojedes'
              value: 'Cojedes'
            - name: 'Delta Amacuro'
              value: 'Delta Amacuro'
            - name: 'Distrito Capital'
              value: 'Distrito Capital'
            - name: 'Falcón'
              value: 'Falcón'
            - name: 'Guárico'
              value: 'Guárico'
            - name: 'Lara'
              value: 'Lara'
            - name: 'La Guaira'
              value: 'La Guaira'
            - name: 'Mérida'
              value: 'Mérida'
            - name: 'Miranda'
              value: 'Miranda'
            - name: 'Monagas'
              value: 'Monagas'
            - name: 'Nueva Esparta'
              value: 'Nueva Esparta'
            - name: 'Portuguesa'
              value: 'Portuguesa'
            - name: 'Sucre'
              value: 'Sucre'
            - name: 'Táchira'
              value: 'Táchira'
            - name: 'Trujillo'
              value: 'Trujillo'
            - name: 'Yaracuy'
              value: 'Yaracuy'
            - name: 'Zulia'
              value: 'Zulia'
          alterable: false
      - name: phone_number
        field:
          element: text
          label: Ingresa el número de teléfono
          type: text
      - name: address
        field:
          element: text
          label: Ingresa la dirección
          type: text
      - name: website
        field:
          element: text
          label: Ingresa la dirección del sitio web
          type: text
      - name: facebook_user
        field:
          element: text
          label: Ingresa el usuario de Facebook
          type: text
      - name: twitter_user
        field:
          element: text
          label: Ingresa el usuario de Twitter
          type: text
      - name: instagram_user
        field:
          element: text
          label: Ingresa el usuario de Instagram
          type: text
      - name: services
        field:
          element: multiselect
          label: Selecciona los servicios 
          help: Puedes seleccionar varios tipos
          options:
            - name: 'Asesoría Personalizada de Viajes'
              value: 'Asesoría Personalizada de Viajes'
            - name: 'Excursiones Locales'
              value: 'Excursiones Locales'
            - name: 'Guía Turística'
              value: 'Guía Turística'
            - name: 'Hospedaje'
              value: 'Hospedaje'
            - name: 'Organización de Viajes'
              value: 'Organización de Viajes'
            - name: 'Organización de Viajes de Turismo'
              value: 'Organización de Viajes de Turismo'
            - name: 'Resolución de Incidencias'
              value: 'Resolución de Incidencias'
            - name: 'Servicio de Reservación'
              value: 'Servicio de Reservación'
            - name: 'Traslados'
              value: 'Traslados'
            - name: 'Venta de Boletos Aéreos Internacionales'
              value: 'Venta de Boletos Aéreos Internacionales'
            - name: 'Venta de Boletos Aéreos Nacionales'
              value: 'Venta de Boletos Aéreos Nacionales'
            - name: 'Viajes Internacionales'
              value: 'Viajes Internacionales'
            - name: 'Viajes Nacionales'
              value: 'Viajes Nacionales'
          alterable: false
      - name: featured
        field:
          element: checkbox
          label: Publicación destacada
          help: Puedes destacar la publicación en la sección de Directorio
          value: true
      - name: image
        field: 
          element: text
          label: Indica la ruta de la imagen de la publicación
          value: ""
      - name: types
        field:
          element: multiselect
          label: Selecciona el tipo 
          help: Puedes seleccionar varios tipos
          options:
            - name: 'Operadores'
              value: 'Operadores'
            - name: 'Mayoristas'
              value: 'Mayoristas'
            - name: 'Agencias'
              value: 'Agencias'
            - name: 'Hospedaje'
              value: 'Hospedaje'
            - name: 'Alquiler'
              value: 'Alquiler'
            - name: 'Líneas aéreas'
              value: 'Líneas aéreas'
          alterable: false
      - name: resumen
        field:
          element: text
          label: Ingresa el resumen de la reseña
          type: text
    _review:
      - name: layout
        field:
          element: hidden
          value: review
      - name: title
        field:
          element: text
          label: Ingresa el nombre 
          type: text
      - name: date
        field:
          element: text
          label: Fecha de creación
          value: CURRENT_DATETIME
      - name: author
        field: 
          element: text
          label: Nombre del autor
          value: ""
      - name: image
        field: 
          element: text
          label: Indica la ruta de la imagen de la publicación
          value: ""
