---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Boarding Pass
logo: /assets/images/logo-bp.jpg
logo-small: /assets/images/boton-bp.jpg
description: # Add your awesome description
copyright: "Copyright © 2023 Boarding Pass."
# Preloader
preloader: true # To disable preloader change value to false

locale: "es-ES"
timezone: America/Caracas

menu:
  - name: Home
    url: /
  - name: Entérate
    url: /entérate/
  - name: Opinión
    url: /opinión/
  - name: Rutas
    url: /rutas/
    submenu:
     - name: VIP's
       url: /rutas/vips/
     - name: Aérea
       url: /rutas/aerea/
     - name: Marítima
       url: /rutas/maritima/
     - name: Terrestre
       url: /rutas/terrestre/
  - name: Destinos
    url: /destinos/
  - name: Directorio
    url: /directorio/
  - name: Acerca
    url: /acerca/
  - name: Contacto
    url: /contacto/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: Somos un boarding pass p
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Boarding Pass

#-------------------------------
# Contact Info
contact:
  email: contacto@boardingpass.network
  phone: 
  address:
    city: Caracas
    street: 

# Contact Form
contact-form: contacto@boardingpass.network

# Social links
social:
  - { icon: "ti-instagram", link: "https://instagram.com/tuboarding" }
  - { icon: "ti-twitter-alt", link: "https://twitter.com/tuboarding" }
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-linkedin", link: "#" }
  - { icon: "ti-github", link: "https://github.com/boardingpassblog" }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - ".gitignore"

prose:
  ignore: [
    '_layouts',
    '_includes',
    '_site',
    '_pages',
    '.sass-cache',
    '_config.yml',
    '.gitignore',
    '404.html',
    'index.html',
    'assets',
    'CNAME',
    'robots.txt',
    'LICENSE',
    'readme.md',
    'Gemfile',
    'Gemfile.lock'
  ]
  siteurl: "https://boardingpass.network/page/"
  media: 'assets/images/contenido'
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Ingresa el título la publicación
          type: text
      - name: date
        field:
          element: text
          label: Fecha de la publicación
          value: CURRENT_DATETIME
      - name: description
        field:
          element: text
          label: Ingresa la descripción de la publicación
          type: text
      - name: featured
        field:
          element: checkbox
          label: Publicación resaltada
          help: Puedes destacar la pubblicación en la página principal
          value: false
      - name: published
        field:
          element: checkbox
          label: ¿Publicar?
          help: Puedes publicar directamente o dejar como borrador
          value: true
      - name: image
        field: 
          element: text
          label: Indica la ruta de la imagen de la publicación
          value: ""
      - name: author
        field:
          element: select
          label: Selecciona el autor
          help: Puedes seleccionar sólo un autor
          options:
            - name: 'Edgar Rincón'
              value: 'Edgar Rincón'
            - name: 'Ana Iriza'
              value: 'Ana Iriza'
            - name: 'Alexandra Castillo'
              value: 'Alexandra Castillo'
          alterable: false      
      - name: categories
        field:
          element: multiselect
          label: Selecciona las categoría de la publicación
          help: Puedes seleccionar varias categoría
          options:
            - name: 'Destinos'
              value: 'destinos'
            - name: 'Directorio'
              value: 'directorio'
            - name: 'Entérate'
              value: 'entérate'
            - name: 'Opinión'
              value: 'opinión'
            - name: 'Rutas'
              value: 'rutas'
          alterable: false
      - name: ruta
        field:
          element: select
          label: Si es una ruta selecciona el tipo de ruta
          help: Puedes seleccionar un solo tipo
          options:
            - name: "VIP's"
              value: 'vips'
            - name: 'Aérea'
              value: 'aerea'
            - name: 'Marítima'
              value: 'maritima'
            - name: 'Terrestre'
              value: 'terrestre'
          alterable: false