---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Boarding Pass
logo: /assets/images/logo.jpg
logo-small: /assets/images/boton-bp.jpg
description: # Add your awesome description
copyright: "Copyright © 2023 Boarding Pass"
# Preloader
preloader: false # To disable preloader change value to false

locale: "es-ES"
timezone: America/Caracas

menu:
  - name: Home
    url: /
  - name: Entérate
    url: /enterate/
  - name: Opinión
    url: /opinion/
  - name: Rutas
    url: /rutas/
    submenu:
     - name: VIP's
       url: /rutas/vips/
     - name: Aérea
       url: /rutas/aerea/
     - name: Marítima
       url: /rutas/maritima/
     - name: Terrestre
       url: /rutas/terrestre/
  - name: Salte del radar
    url: /salte-del-radar/
  - name: Destinos
    url: /destinos/
  - name: Directorio
    url: /directorio/
  - name: Acerca
    url: /acerca/
  - name: Contacto
    url: /contacto/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: Somos un boarding pass p
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Boarding Pass

#-------------------------------
# Contact Info
contact:
  email: contacto@boardingpass.network
  whatsapp: +58 426 5203724
  walink: 584265203724
  address:
    city: Caracas
    street: 

# Contact Form
contact-form: contacto@boardingpass.network

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: G-3PLT3KJYNC

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
#  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

#Collections
collections:
  directorio:
    output: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - ".gitignore"

prose:
  ignore: [
    '_layouts',
    '_includes',
    '_site',
    '_pages',
    '.sass-cache',
    '_config.yml',
    '.gitignore',
    '404.html',
    'index.html',
    'assets',
    'CNAME',
    'robots.txt',
    'LICENSE',
    'readme.md',
    'Gemfile',
    'Gemfile.lock'
  ]
  siteurl: "https://boardingpass.network/page/"
  media: 'assets/images/contenido'
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Ingresa el título la publicación
          type: text
      - name: date
        field:
          element: text
          label: Fecha de la publicación
          value: CURRENT_DATETIME
      - name: description
        field:
          element: text
          label: Ingresa la descripción de la publicación
          type: text
      - name: featured
        field:
          element: checkbox
          label: Publicación resaltada
          help: Puedes destacar la publicación en la página principal
          value: false
      - name: published
        field:
          element: checkbox
          label: ¿Publicar?
          help: Puedes publicar directamente o dejar como borrador
          value: true
      - name: image
        field: 
          element: text
          label: Indica la ruta de la imagen de la publicación
          value: ""
      - name: image-text
        field: 
          element: text
          label: Indica el texto que describe la foto
          value: ""
      - name: banner-image
        field: 
          element: text
          label: Indica la ruta del banner
          value: ""
      - name: banner-alt
        field: 
          element: text
          label: Indica el texto alternativo del banner
          value: ""
      - name: banner-url
        field: 
          element: text
          label: Indica el link del banner
          value: ""
      - name: author
        field:
          element: text
          label: Nombre del autor
          value: ""
      - name: categories
        field:
          element: multiselect
          label: Selecciona las categoría de la publicación
          help: Puedes seleccionar varias categoría
          options:
            - name: 'Destinos'
              value: 'destinos'
            - name: 'Directorio'
              value: 'directorio'
            - name: 'Entérate'
              value: 'enterate'
            - name: 'Opinión'
              value: 'opinion'
            - name: 'Rutas'
              value: 'rutas'
            - name: 'Salte del radar'
              value: 'salte-del-radar'
          alterable: false
      - name: ruta
        field:
          element: select
          label: Si es una ruta selecciona el tipo de ruta
          help: Puedes seleccionar un solo tipo
          options:
            - name: "VIP's"
              value: 'vips'
            - name: 'Aérea'
              value: 'aerea'
            - name: 'Marítima'
              value: 'maritima'
            - name: 'Terrestre'
              value: 'terrestre'
          alterable: false
    _directorio:
      - name: name
        field:
          element: text
          label: Ingresa el nombre 
          type: text
      - name: date
        field:
          element: text
          label: Fecha de creación
          value: CURRENT_DATETIME
      - name: region
        field:
          element: text
          label: Ingresa la Región
          type: text
      - name: state
        field:
          element: text
          label: Ingresa el Estado
          type: text
      - name: sector
        field:
          element: text
          label: Ingresa el Sector
          type: text
      - name: phone_number
        field:
          element: text
          label: Ingrese el número de teléfono
          type: text
      - name: address
        field:
          element: text
          label: Ingresa la dirección
          type: text
      - name: web_page
        field:
          element: text
          label: Ingresa la página web
          type: text
      - name: facebook_page
        field:
          element: text
          label: Ingresa la página de Facebook
          type: text
      - name: twitter_page
        field:
          element: text
          label: Ingresa la página de Twitter
          type: text
      - name: instagram_page
        field:
          element: text
          label: Ingresa la página de Instagram
          type: text
      - name: services
        field:
          element: text
          label: Ingresa los servicios
          type: text
      - name: featured
        field:
          element: checkbox
          label: Publicación destacada
          help: Puedes destacar la publicación en la sección de Directorio
          value: true
      - name: image
        field: 
          element: text
          label: Indica la ruta de la imagen de la publicación
          value: ""
      - name: types
        field:
          element: multiselect
          label: Selecciona el tipo 
          help: Puedes seleccionar varios tipos
          options:
            - name: 'Operadores'
              value: 'operadores'
            - name: 'Mayoristas'
              value: 'mayoristas'
            - name: 'Agencias'
              value: 'agencias'
            - name: 'Hospedaje'
              value: 'hospedaje'
            - name: 'Alquiler'
              value: 'alquiler'
          alterable: false